### ISSUE TITLE
Interface clean up

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-interfaces#66]
There are currently some parts of the interface design that have redundant arguments, etc:

 - ~~In the block client interface an incoming response is retrieved by the `Next` function. if it is a read response the data can be retrieved by calling `Read` on this request. It then has to be acknowledged by calling `Release` after which the platform discards it. Both `Read` and `Release` require the request as argument although no other request than the one returned by `Next` is available for handling. Therefor it doen't need to be passed as an argument.~~ (obsoleted by new interface, cf. #69)

 - ~~A similar problem exists for the block server. While the `Discard` procedure already doesn't take the request as argument the `Read`, `Write` and `Acknowledge` procedures do. They also depend on the request returned by `Head` which also implements a FIFO Queue so only the first element is available. Either the response path needs to be separated from the request path to provide the ability to acknowledge out of order (which is desirable) or only first request in the queue can be responded at a time.~~ (obsoleted by new interface, cf. #69)

 - ~~The block dispatcher provides a session label with the `Session_Request` procedure. This label can be used to identify the requesting client. It is then passed to the `Session_Accept` procedure. Inbetween it could have been changed. Since `Session_Accept` uses the label to identify the actual session to connect the label shouldn't be changed as any other session is probably not available or cannot be safely connected to. This information should be instead passed via the dispatcher capability~~ (moved to #50).

**Comment by senier** [comment]
Obsoleted by other tickets, closing
